// This file has been generated by zoltan (https://github.com/jac3km4/zoltan)

#define ZOLTAN_STRINGISE(N) #N
#define ZOLTAN_EXPAND_THEN_STRINGISE(N) ZOLTAN_STRINGISE(N)
#define __LINE_STR__ ZOLTAN_EXPAND_THEN_STRINGISE(__LINE__)

#ifndef AssertionFailed_Addr
#define AssertionFailed_Addr 0x29387E8
#endif
#ifndef Breakpoint_Addr
#define Breakpoint_Addr 0x2026C1C
#endif
#ifndef CrashFunc_Addr
#define CrashFunc_Addr 0x2939C64
#endif
#ifndef InvokeStatic_Addr
#define InvokeStatic_Addr 0x13254C
#endif
#ifndef InvokeVirtual_Addr
#define InvokeVirtual_Addr 0x51A24C
#endif
#ifndef Murmur3_32_Addr
#define Murmur3_32_Addr 0x72CB0C
#endif
#ifndef ScriptHost_Get_Addr
#define ScriptHost_Get_Addr 0xFF478
#endif
#ifndef ScriptHost_VFT_Addr
#define ScriptHost_VFT_Addr 0x2A22010
#endif
#ifndef ScriptInterface_VFT_Addr
#define ScriptInterface_VFT_Addr 0x2A22000
#endif
#ifndef ShowMessageBox_Addr
#define ShowMessageBox_Addr 0x21D8E0C
#endif
